name = "BroadSearch"
uuid = "a5f28154-e214-4474-a204-cf7c4b025408"
authors = ["Burton Yale <burtonyale+github@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
